version: '3'
services:
  app:
    build: ./
    ports:
      - '3000:3000'
    environment:
      - SERVER_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=conexa_user
      - DB_PASSWORD=secretpassword
      - DB_NAME=conexa_db
      - JWT_SECRETPW=jwtpassword
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=conexa_user
      - POSTGRES_DB=conexa_db

volumes:
  pgdata:
